### ISSUE TITLE
Hurry up!

### ISSUE THREAD

**Issue by El-Zipo** [Madh93/oranchelo-icon-theme#6]
Please hurry up!
I'm waiting for new version.

**Comment by Madh93** [comment]
Hi, sorry for the waiting. 

But i just i package the sources and i distribute it. I have told the [original author](http://zayronxio.deviantart.com/art/Oranchelo-icons-beta-v0-7-2-567346368) about this issues but at this moment there is not information about the next release :disappointed:

**Comment by WantedFish** [comment]
:( OK.
Hurry!!!!!1

**Comment by Madh93** [comment]
New minor version :+1:

**Comment by El-Zipo** [comment]
Thank you soooo much.
Add this to gnome-look.org
Then this theme will be more popular.

**Comment by El-Zipo** [comment]
Or May I add this theme to gnome-look.org?

**Comment by Madh93** [comment]
[zayronXIO](https://www.gnome-look.org/member/240113/) uploaded a first version last year, but is outdated. You could add a new project with last version :+1:

**Comment by El-Zipo** [comment]
Added to gnome-look
Checkout this @Madh93 
[https://www.gnome-look.org/p/1151268/](url)

**Comment by Madh93** [comment]
Page not found, is the correct link?

**Comment by El-Zipo** [comment]
I already added this theme to gnome-look
![screenshot from 2016-08-15 11-25-26](https://cloud.githubusercontent.com/assets/19838220/17669282/164170d0-62db-11e6-9db3-7c959a4221c2.png)

It's still not showing in the gnome-look home page. But it's listed in "My Products" list.

**Comment by El-Zipo** [comment]
Look at the URL of the address bar. That's the same address that provided to you.
![screenshot from 2016-08-15 11-29-24](https://cloud.githubusercontent.com/assets/19838220/17669412/8e515d4c-62db-11e6-9cdd-fc946ccab54e.png)


But it's still not showing my profile
![screenshot from 2016-08-15 11-31-40](https://cloud.githubusercontent.com/assets/19838220/17669509/e3f6352e-62db-11e6-8c37-946c29f086fb.png)


And also not showing in the site's home page
![screenshot from 2016-08-15 11-34-19](https://cloud.githubusercontent.com/assets/19838220/17669598/3c00cf7c-62dc-11e6-951d-a03786b565de.png)

There having lot of issues after upgrading the user interface of gnome-look web site.
I think it's an issue. There's no any new product added since 5 hours. :(

**Comment by El-Zipo** [comment]
I'm really sorry

**Comment by Madh93** [comment]
Don't worry, thank you for added to gnome-look. Sure tomorrow works :+1:

**Comment by El-Zipo** [comment]
Uploaded it again.
This is the new link. Now it's online
[https://www.gnome-look.org/p/1151321/](url)

**Comment by El-Zipo** [comment]
https://www.gnome-look.org/p/1151321/
Uploaded it again.
@Madh93 check this.

**Comment by Madh93** [comment]
Works great!

**Comment by El-Zipo** [comment]
thanks
